### ISSUE TITLE
朋友能问下股票实时刷新表格是怎么实现的吗

### ISSUE THREAD

**Issue by TildaWatts** [jezzmemo/JJStockView#1]
用的websocket，每次推过来的是部分数据，更新数据显示在tableview里呢，如果用reloaddata的话，整体会更新

**Comment by jezzmemo** [comment]
因为我的真正不是应用在股票上，从技术上角度来说刷新是选择reloadAtRow上的，从而让刷新的东西尽量少，而且控制在可视范围内，这样就会控制刷新的东西少，还有注意一个体验就是，刷新的希望就是停留在当前的位置上，这样就不会有跳动的体验，暂时就想到这么多。

**Comment by jezzmemo** [comment]
@TildaWatts

**Comment by jezzmemo** [comment]
@TildaWatts 最近把整个工程完善了下，你的问题得到一个好的解决方案是通过visibleCells获取可见cell，用最新的数据，把需要刷新的cell，更新下UI，这样就不会有闪动的体验，变化比较平滑，效果比较好。
