### ISSUE TITLE
Can we do it in swift 3?

### ISSUE THREAD

**Issue by sameerkupkar** [jezzmemo/JJStockView#3]

**Comment by jezzmemo** [comment]
use the bridge that the swift invoke the objective-c class and method

**Comment by sameerkupkar** [comment]
Thanks.

**Comment by sameerkupkar** [comment]
Can we add  Search bar for  searching data and one column have spark chart it is possible ?

**Comment by jezzmemo** [comment]
I will add head view and foot view for next release

**Comment by sameerkupkar** [comment]
When it will come let me know please. Waiting for your reply.

**Comment by jezzmemo** [comment]
@sameerkupkar 
I had add the head and foot for JJStockView,please update

**Comment by sameerkupkar** [comment]
Thanks .

Warm Regards
Sameer D. Kupkar
Cell:- +91-9096620267
Email:- sameerkupkar@gmail.com

**Comment by jezzmemo** [comment]
# 6936b9432623b3bcada69646c682675b4c680bf2
